### ISSUE TITLE
Final Peer Review

### ISSUE THREAD

**Issue by a-Leong** [dancyfang/HousePrice#12]
This project aims to predict real estate values in Manhattan using data from the New York City Department of City Planning. The resulting models will be used to estimate asset values for real estate companies and provide suggestions for city planning for New York state. The report is well put together and features numerous plots which are pleasing to the eye. Additionally, the group's process is well documented and gives a good sense of how the project developed over time. It is apparent that a respectable amount of work went into the models and the report, and the project developed with respect to methods exhibited in lecture.

I was only left with a few concerns. First, the results of the project did not seem to provide any insight into Manhattan real estate values; larger properties having more value seems like a trivial conclusion. That being said, the two stage model appears to do a very good job of predicting value. I would have liked to see a more generally understandable model accuracy assessment besides MSE (which is not usually interpretable if one is unfamiliar with the data), for example, how often does the model correctly predict real estate value within a 5% margin? The abstract could benefit from such a metric. 

Overall, good work.

**Comment by dancyfang** [comment]
Thank you for your comment!
We will think more about how to interpret model results in a more meaningful and interesting way. And your suggestion on evaluation metrics is also great.
